In [1]:
import numpy as np
import pandas as pd

In [2]:
obj = pd.Series([[4, 5], [5, 6]])

In [3]:
obj

0    [4, 5]
1    [5, 6]
dtype: object

In [4]:
obj.values

array([list([4, 5]), list([5, 6])], dtype=object)

In [5]:
obj.index

RangeIndex(start=0, stop=2, step=1)

In [6]:
obj = pd.Series([4, 7, -5, 3])

In [7]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [8]:
obj.values

array([ 4,  7, -5,  3])

In [9]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [10]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [11]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [12]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [13]:
obj2['a']

-5

In [14]:
obj2['d'] = 6

In [15]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [16]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [17]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [18]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [19]:
'b' in obj2

True

In [20]:
'e' in obj2

False

In [21]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon':16000, 'Utah': 5000}

In [22]:
obj3 = pd.Series(sdata)

In [23]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [24]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [25]:
obj4 = pd.Series(sdata, index=states)

In [26]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [27]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [28]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [29]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [30]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [31]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [32]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [33]:
obj4.name = 'population'

In [34]:
obj4.index.name = 'state'

In [35]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [36]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [37]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [38]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [39]:
data = {
    'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
    'year': [2000, 2001, 2002, 2001, 2002, 2003],
    'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}

In [40]:
frame = pd.DataFrame(data)

In [41]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [42]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [43]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [44]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                     index=['one', 'two', 'three', 'four', 'five', 'six'])

In [45]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [46]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [47]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [48]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [49]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [50]:
frame2['debt'] = 16.5

In [51]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [52]:
frame2['debt'] = np.arange(6.)

In [53]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [54]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [55]:
frame2['pop'] = val

In [56]:
frame2

year   state  pop  debt
one    2000    Ohio  NaN   0.0
two    2001    Ohio -1.2   1.0
three  2002    Ohio  NaN   2.0
four   2001  Nevada -1.5   3.0
five   2002  Nevada -1.7   4.0
six    2003  Nevada  NaN   5.0

In [57]:
frame2['eastern'] = frame2.state == 'Ohio'

In [58]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  NaN   0.0     True
two    2001    Ohio -1.2   1.0     True
three  2002    Ohio  NaN   2.0     True
four   2001  Nevada -1.5   3.0    False
five   2002  Nevada -1.7   4.0    False
six    2003  Nevada  NaN   5.0    False

In [59]:
del frame2['eastern']

In [60]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [61]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
      'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [62]:
frame3 = pd.DataFrame(pop)

In [63]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [64]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [65]:
pd.DataFrame(pop, columns=['Ohio', 'Nevada'], index=[2001, 2002, 2003])

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [66]:
pdata = {'Ohio': frame3['Ohio'][:-1], 'Nevada': frame3['Nevada'][:2]}

In [67]:
pdata

{'Ohio': 2000    1.5
 2001    1.7
 Name: Ohio, dtype: float64, 'Nevada': 2000    NaN
 2001    2.4
 Name: Nevada, dtype: float64}

In [68]:
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [69]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [70]:
frame3.index.name = 'year'

In [71]:
frame3.columns.name = 'state'

In [72]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [73]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [74]:
frame2.values

array([[2000, 'Ohio', nan, 0.0],
       [2001, 'Ohio', -1.2, 1.0],
       [2002, 'Ohio', nan, 2.0],
       [2001, 'Nevada', -1.5, 3.0],
       [2002, 'Nevada', -1.7, 4.0],
       [2003, 'Nevada', nan, 5.0]], dtype=object)

In [75]:
x = np.array([(1,2.,'Hello'), (2,3.,"World")], dtype=[('foo', 'i4'),('bar', 'f4'), ('baz', 'S10')])

In [76]:
x['foo']

array([1, 2], dtype=int32)

In [77]:
pd.DataFrame(x)

foo  bar       baz
0    1  2.0  b'Hello'
1    2  3.0  b'World'

In [78]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [79]:
index = obj.index

In [80]:
index

Index(['a', 'b', 'c'], dtype='object')

In [81]:
index[1:]

Index(['b', 'c'], dtype='object')

In [82]:
arr = obj.values

In [83]:
arr

array([0, 1, 2])

In [84]:
arr[0] = 3

In [85]:
obj

a    3
b    1
c    2
dtype: int64

In [86]:
labels = pd.Index(np.arange(3))

In [87]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [88]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [89]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [90]:
obj2.index is labels

True

In [91]:
obj2.index == labels

array([ True,  True,  True])

In [92]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [93]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [94]:
'Ohio' in frame3.columns

True

In [95]:
2003 in frame3.index

False

In [96]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [97]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [98]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [99]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [100]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [101]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [102]:
obj3.reindex(range(0, 10, 2), method='ffill', tolerance=2)

0      blue
2    purple
4    yellow
6    yellow
8       NaN
dtype: object

In [103]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                    index=['a', 'c', 'b'],
                    columns=['Ohio', 'Texas', 'California'])

In [104]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
b     6      7           8

In [105]:
frame2 = frame.reindex(['a', 'b', 'c'])

In [106]:
frame2

Ohio  Texas  California
a     0      1           2
b     6      7           8
c     3      4           5

In [107]:
states = ['Texas', 'California', 'Utah']

In [108]:
frame.reindex(columns=states)

Texas  California  Utah
a      1           2   NaN
c      4           5   NaN
b      7           8   NaN

In [109]:
frame.loc['a']

Ohio          0
Texas         1
California    2
Name: a, dtype: int64

In [110]:
frame['California']

a    2
c    5
b    8
Name: California, dtype: int64

In [111]:
frame.loc[['a', 'b']]['Ohio']

a    0
b    6
Name: Ohio, dtype: int64

In [112]:
obj = pd.Series(np.arange(5.0), index=['a', 'b', 'c', 'd', 'e'])

In [113]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [114]:
new_obj = obj.drop('c')

In [115]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [116]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [117]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])

In [118]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [119]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [120]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [121]:
obj.drop('c', inplace=True)

In [122]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [123]:
obj = pd.Series(np.arange(4.), index=['a', 'c', 'b', 'd'])

In [124]:
obj

a    0.0
c    1.0
b    2.0
d    3.0
dtype: float64

In [125]:
obj['b']

2.0

In [126]:
obj[1]

1.0

In [127]:
obj[2:4]

b    2.0
d    3.0
dtype: float64

In [128]:
obj['a':'b']

a    0.0
c    1.0
b    2.0
dtype: float64

In [129]:
obj[['b', 'a' ,'d']]

b    2.0
a    0.0
d    3.0
dtype: float64

In [130]:
obj[[1, 3]]

c    1.0
d    3.0
dtype: float64

In [131]:
obj[obj<2]

a    0.0
c    1.0
dtype: float64

In [132]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [133]:
data.loc[['Ohio', 'Colorado'], ['one', 'two']]

one  two
Ohio        0    1
Colorado    4    5

In [134]:
obj['a':'b'] = 4

In [135]:
obj

a    4.0
c    4.0
b    4.0
d    3.0
dtype: float64

In [136]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])

In [137]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [138]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [139]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [140]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [141]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [142]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [143]:
data[data < 5]

one  two  three  four
Ohio      0.0  1.0    2.0   3.0
Colorado  4.0  NaN    NaN   NaN
Utah      NaN  NaN    NaN   NaN
New York  NaN  NaN    NaN   NaN

In [144]:
data[data < 5] = 0

In [145]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [146]:
arr2d = np.arange(16).reshape((4, 4))

In [147]:
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [148]:
arr2d < 5

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [149]:
arr2d[arr2d < 5]

array([0, 1, 2, 3, 4])

In [150]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [151]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [152]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [153]:
arr2d[1 : 3, [1, 3]]

array([[ 5,  7],
       [ 9, 11]])

In [154]:
arr2d[[1, 3], [1, 3]]

array([ 5, 15])

In [155]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [156]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [157]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [158]:
data[['one', 'two']]

one  two
Ohio        0    0
Colorado    0    5
Utah        8    9
New York   12   13

In [159]:
ser = pd.Series(np.arange(3.))

In [160]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [161]:
ser[1]

1.0

In [162]:
ser[:1]

0    0.0
dtype: float64

In [163]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [164]:
ser.iloc[:1]

0    0.0
dtype: float64

In [165]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [166]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [167]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [168]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [169]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                  index=['Ohio', 'Texas', 'Colorado'])

In [170]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [171]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [172]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [173]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [174]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})

In [175]:
df1

A
0  1
1  2

In [176]:
df2

B
0  3
1  4

In [177]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [178]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                  columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                  columns=list('abcde'))

In [179]:
df2.at[0, 'e'] = np.nan

In [180]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [181]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   NaN
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [182]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [183]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   NaN
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [184]:
df2.add(df1, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   NaN
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [185]:
1 / df1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [186]:
df1.rdiv(1)

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [187]:
df1.reindex(columns=df2.columns)

a    b     c     d   e
0  0.0  1.0   2.0   3.0 NaN
1  4.0  5.0   6.0   7.0 NaN
2  8.0  9.0  10.0  11.0 NaN

In [188]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [189]:
np.arange(3) + np.arange(9).reshape((3, 3))

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [190]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [191]:
arr[0]

array([0., 1., 2., 3.])

In [192]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [193]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                    columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [194]:
series = frame.iloc[0]

In [195]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [196]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [197]:
series[1] = 2

In [198]:
frame

b     d     e
Utah    0.0   2.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [199]:
series[1] = 1

In [200]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [201]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [202]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [203]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [204]:
series3 = frame['d']

In [205]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [206]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [207]:
frame.sub(series3, axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [208]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [209]:
frame

b         d         e
Utah    1.735674 -0.559752 -0.348762
Ohio   -0.364770 -0.997585 -1.351314
Texas  -2.338758 -0.408347 -0.685978
Oregon  0.219450  1.891081  0.106595

In [210]:
np.abs(frame)

b         d         e
Utah    1.735674  0.559752  0.348762
Ohio    0.364770  0.997585  1.351314
Texas   2.338758  0.408347  0.685978
Oregon  0.219450  1.891081  0.106595

In [211]:
frame.max(axis='columns')

Utah      1.735674
Ohio     -0.364770
Texas    -0.408347
Oregon    1.891081
dtype: float64

In [212]:
f = lambda x : x.max() - x.min()

In [213]:
frame.apply(f)

b    4.074432
d    2.888666
e    1.457909
dtype: float64

In [214]:
frame.apply(f, axis='columns')

Utah      2.295426
Ohio      0.986544
Texas     1.930410
Oregon    1.784487
dtype: float64

In [215]:
f = lambda x : pd.Series([x.min(), x.max()], index=['min', 'max'])

In [216]:
frame.apply(f)

b         d         e
min -2.338758 -0.997585 -1.351314
max  1.735674  1.891081  0.106595

In [217]:
format = lambda x : '%.2f' % x

In [218]:
frame.applymap(format)

b      d      e
Utah     1.74  -0.56  -0.35
Ohio    -0.36  -1.00  -1.35
Texas   -2.34  -0.41  -0.69
Oregon   0.22   1.89   0.11

In [219]:
frame['e'].map(format)

Utah      -0.35
Ohio      -1.35
Texas     -0.69
Oregon     0.11
Name: e, dtype: object

In [220]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [221]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [222]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                    index=['three', 'one'],
                    columns=['d', 'a', 'b', 'c'])

In [223]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [224]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [225]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [226]:
obj = pd.Series([4, 7, -3, 2])

In [227]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [228]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [229]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [230]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [231]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [232]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [233]:
frame.sort_values(by=1, axis=1)

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [234]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [235]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [236]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [237]:
obj.rank(ascending=False, method='min')

0    1.0
1    7.0
2    1.0
3    3.0
4    5.0
5    6.0
6    3.0
dtype: float64

In [238]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                     'c': [-2, 5, 8, -2.5]})

In [239]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [240]:
frame.rank()

b    a    c
0  3.0  1.5  2.0
1  4.0  3.5  3.0
2  1.0  1.5  4.0
3  2.0  3.5  1.0

In [241]:
frame.rank(axis=1)

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [242]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [243]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [244]:
obj.index.is_unique

False

In [245]:
obj['a']

a    0
a    1
dtype: int64

In [246]:
obj['c']

4

In [247]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [248]:
df

0         1         2
a  0.783998  0.674858  1.091859
a -1.256989 -1.400091  1.345045
b  1.172306  0.173557 -0.055624
b -0.177438 -0.164222 -1.080744

In [249]:
df.loc['b']

0         1         2
b  1.172306  0.173557 -0.055624
b -0.177438 -0.164222 -1.080744

In [250]:
np.max(np.arange(9).reshape((3, 3)))

8

In [251]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                 index=['a', 'b', 'c', 'd'],
                 columns=['one', 'two'])

In [252]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [253]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [254]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [255]:
df.mean(axis=1, skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [256]:
df.idxmax()

one    b
two    d
dtype: object

In [257]:
df['one'].argmax()

/home/trierbo/miniconda2/envs/pydata/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: 'argmax' is deprecated, use 'idxmax' instead. The behavior of 'argmax'
will be corrected to return the positional maximum in the future.
Use 'series.values.argmax' to get the position of the maximum now.
  """Entry point for launching an IPython kernel.


'b'

In [258]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [259]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [260]:
obj = pd.Series(['a', 'b', 'b', 'c'] * 4)

In [261]:
obj

0     a
1     b
2     b
3     c
4     a
5     b
6     b
7     c
8     a
9     b
10    b
11    c
12    a
13    b
14    b
15    c
dtype: object

In [262]:
obj.describe()

count     16
unique     3
top        b
freq       8
dtype: object

In [263]:
import pandas_datareader.data as web
import fix_yahoo_finance as fyf

fyf.pdr_override()

In [264]:
all_data = {ticker: web.get_data_yahoo(ticker)
           for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded


In [265]:
price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

In [266]:
price.tail()

AAPL         IBM        MSFT         GOOG
Date                                                       
2018-09-13  226.410004  148.949997  112.910004  1175.329956
2018-09-14  223.839996  148.330002  113.370003  1172.530029
2018-09-17  217.880005  147.940002  112.139999  1156.050049
2018-09-18  218.240005  148.559998  113.209999  1161.219971
2018-09-19  218.369995  149.059998  111.699997  1171.089966

In [267]:
volume.tail()

AAPL      IBM        MSFT       GOOG
Date                                                  
2018-09-13  41706400.0  5346500  26055600.0  1431200.0
2018-09-14  31999300.0  3452100  19122300.0   944000.0
2018-09-17  37195100.0  3551900  20736500.0  1306500.0
2018-09-18  31571700.0  3629400  22170900.0  1203600.0
2018-09-19  27107000.0  4246200  21664600.0  1185300.0

In [268]:
returns = price.pct_change()

In [269]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2018-09-13  0.024155  0.016238  0.010742  0.010758
2018-09-14 -0.011351 -0.004162  0.004074 -0.002382
2018-09-17 -0.026626 -0.002629 -0.010849 -0.014055
2018-09-18  0.001652  0.004191  0.009542  0.004472
2018-09-19  0.000596  0.003366 -0.013338  0.008500

- 样本协方差
$cov(x,y) = \frac{1}{n}\sum_i^n{(x_i-\overline{x})(y_i-\overline{y})}$
- 相关系数
$corr(x,y) = \frac{cov(x,y)}{\sqrt{var(x)var(y)}}$

In [270]:
returns['MSFT'].corr(returns['IBM'])

0.4354846912531897

In [271]:
returns['MSFT'].cov(returns['IBM'])

0.00016170765304160338

In [272]:
returns.columns

Index(['AAPL', 'IBM', 'MSFT', 'GOOG'], dtype='object')

In [273]:
returns.index

DatetimeIndex(['1962-01-02', '1962-01-03', '1962-01-04', '1962-01-05',
               '1962-01-08', '1962-01-09', '1962-01-10', '1962-01-11',
               '1962-01-12', '1962-01-15',
               ...
               '2018-09-06', '2018-09-07', '2018-09-10', '2018-09-11',
               '2018-09-12', '2018-09-13', '2018-09-14', '2018-09-17',
               '2018-09-18', '2018-09-19'],
              dtype='datetime64[ns]', name='Date', length=14278, freq=None)

In [274]:
returns.index.name = 'Date'

In [275]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2018-09-13  0.024155  0.016238  0.010742  0.010758
2018-09-14 -0.011351 -0.004162  0.004074 -0.002382
2018-09-17 -0.026626 -0.002629 -0.010849 -0.014055
2018-09-18  0.001652  0.004191  0.009542  0.004472
2018-09-19  0.000596  0.003366 -0.013338  0.008500

In [276]:
returns.name = 'stock'

In [277]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2018-09-13  0.024155  0.016238  0.010742  0.010758
2018-09-14 -0.011351 -0.004162  0.004074 -0.002382
2018-09-17 -0.026626 -0.002629 -0.010849 -0.014055
2018-09-18  0.001652  0.004191  0.009542  0.004472
2018-09-19  0.000596  0.003366 -0.013338  0.008500

In [278]:
returns.MSFT.corr(returns.IBM)

0.4354846912531897

In [279]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.357109  0.387551  0.454109
IBM   0.357109  1.000000  0.435485  0.390086
MSFT  0.387551  0.435485  1.000000  0.466494
GOOG  0.454109  0.390086  0.466494  1.000000

In [280]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000859  0.000176  0.000239  0.000180
IBM   0.000176  0.000251  0.000162  0.000098
MSFT  0.000239  0.000162  0.000462  0.000145
GOOG  0.000180  0.000098  0.000145  0.000364

In [281]:
returns.corrwith(returns.iloc[:, 1:3])

AAPL    NaN
GOOG    NaN
IBM     1.0
MSFT    1.0
dtype: float64

In [282]:
returns.corrwith(volume)

AAPL   -0.002306
IBM    -0.000468
MSFT   -0.004207
GOOG    0.047362
dtype: float64

In [283]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [284]:
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

In [285]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [286]:
obj.value_counts(sort=False)

d    1
a    3
c    3
b    2
dtype: int64

In [287]:
pd.value_counts(obj.values, sort=False)

d    1
a    3
c    3
b    2
dtype: int64

In [288]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [289]:
mask = obj.isin(['b', 'c'])

In [290]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [291]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [292]:
df1 = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df2 = pd.DataFrame([[1, 20, 3], [4, 50, 6], [7, 80, 9]])

In [293]:
df1.isin(df2)

0      1     2
0  True  False  True
1  True  False  True
2  True  False  True

In [294]:
df1 = pd.DataFrame(np.arange(16).reshape((4, 4)))
df2 = pd.DataFrame(np.arange(25).reshape((5, 5)))

In [295]:
mask = df2.isin(df1)

In [296]:
df2[mask]

0    1    2    3   4
0  0.0  1.0  2.0  3.0 NaN
1  NaN  NaN  NaN  NaN NaN
2  NaN  NaN  NaN  NaN NaN
3  NaN  NaN  NaN  NaN NaN
4  NaN  NaN  NaN  NaN NaN

In [297]:
df2.isin?

In [298]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])

In [299]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2])

In [300]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                    'Qu2': [2, 3, 1, 2, 3],
                    'Qu3': [1, 6, 2, 4, 4]})

In [301]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    6
2    4    1    2
3    3    2    4
4    4    3    4

In [302]:
result = data.apply(pd.value_counts).fillna(0)

In [303]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
6  0.0  0.0  1.0