In [2]:
import numpy as np

### NumPy 标准数据类型
![dtypes](./pics/numpy_dtypes.png)

In [3]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [4]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [5]:
np.zeros(10, dtype='float16')

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float16)

### NumPy 数组的属性

In [6]:
np.random.seed(42)

In [19]:
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

In [8]:
x1

array([6, 3, 7, 4, 6, 9])

In [9]:
x2

array([[2, 6, 7, 4],
       [3, 7, 7, 2],
       [5, 4, 1, 7]])

In [13]:
print('x3 ndim: ', x3.ndim)
print('x3 shape: ', x3.shape)
print('x3 size: ', x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [14]:
print('x3 dtype: ', x3.dtype)

x3 dtype:  int64


- 每个数组元素字节大小的`itemsize`
- 表示数组总字节大小的属性`nbytes`

In [15]:
print('x3 itemsize: ', x3.itemsize)
print('x3 nbytes: ', x3.nbytes)

x3 itemsize:  8
x3 nbytes:  480


数组切片返回的是数组数据的**视图**,而不是数值数据的**副本**

In [42]:
x2

array([[1, 2, 2, 0],
       [3, 4, 2, 0],
       [4, 9, 6, 9]])

In [29]:
x2_sub = x2[:2, :2]

In [21]:
x2_sub

array([[7, 7],
       [7, 2]])

In [33]:
x2_sub[:, :] = [[1, 2], [3, 4]]

In [34]:
x2

array([[1, 2, 2, 0],
       [3, 4, 2, 0],
       [4, 9, 6, 9]])

In [35]:
x2_sub

array([[1, 2],
       [3, 4]])

In [36]:
x2_sub_copy = x2[:2, :2].copy()

In [38]:
x2_sub_copy

array([[1, 2],
       [3, 4]])

In [40]:
x2_sub_copy[:, :] = [[2, 3], [4, 5]]

In [41]:
x2

array([[1, 2, 2, 0],
       [3, 4, 2, 0],
       [4, 9, 6, 9]])

### 数组的变形

In [46]:
grid = np.arange(1, 10).reshape((3, 3))

In [47]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

将一个一维数组转变为二维的行或列的矩阵`newaxis`

In [49]:
x = np.arange(10)

In [50]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [51]:
x[np.newaxis, :]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

### 数组拼接和分裂
#### 数组的拼接
- `np.concatenate`
- `np.vstack` // 第一维度
- `np.hstack` // 第二维度
- `np.dstack` // 第三维度

In [52]:
x = np.arange(1, 10)
y = np.arange(0, 9)

In [56]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8])

In [57]:
x = np.arange(1, 10).reshape((3, 3))
y = np.arange(0, 9).reshape((3, 3))

In [58]:
np.concatenate([x, y])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [59]:
np.concatenate([x, y], axis=1)

array([[1, 2, 3, 0, 1, 2],
       [4, 5, 6, 3, 4, 5],
       [7, 8, 9, 6, 7, 8]])

In [68]:
x = np.arange(1, 28).reshape((3, 3, 3))
y = np.arange(0, 18).reshape((3, 2, 3))

In [69]:
np.concatenate([x, y], axis=1)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27],
        [12, 13, 14],
        [15, 16, 17]]])

In [71]:
x = np.arange(1, 10).reshape((3, 3))
y = np.arange(0, 9).reshape((3, 3))
np.vstack([x, y])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [72]:
np.hstack([x, y])

array([[1, 2, 3, 0, 1, 2],
       [4, 5, 6, 3, 4, 5],
       [7, 8, 9, 6, 7, 8]])

In [73]:
x = np.arange(1, 28).reshape((3, 3, 3))
y = np.arange(0, 27).reshape((3, 3, 3))

In [74]:
np.vstack([x, y])

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [75]:
np.hstack([x, y])

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [76]:
np.dstack([x, y])

array([[[ 1,  2,  3,  0,  1,  2],
        [ 4,  5,  6,  3,  4,  5],
        [ 7,  8,  9,  6,  7,  8]],

       [[10, 11, 12,  9, 10, 11],
        [13, 14, 15, 12, 13, 14],
        [16, 17, 18, 15, 16, 17]],

       [[19, 20, 21, 18, 19, 20],
        [22, 23, 24, 21, 22, 23],
        [25, 26, 27, 24, 25, 26]]])

#### 数组的分裂
- `np.split`
- `np.hsplit`
- `np.vsplit`

In [77]:
x = np.arange(0, 27).reshape((3, 3, 3))

In [78]:
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [79]:
np.split(x, [2], axis=2)

[array([[[ 0,  1],
         [ 3,  4],
         [ 6,  7]],
 
        [[ 9, 10],
         [12, 13],
         [15, 16]],
 
        [[18, 19],
         [21, 22],
         [24, 25]]]), array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

In [80]:
np.hsplit(x, [2])

[array([[[ 0,  1,  2],
         [ 3,  4,  5]],
 
        [[ 9, 10, 11],
         [12, 13, 14]],
 
        [[18, 19, 20],
         [21, 22, 23]]]), array([[[ 6,  7,  8]],
 
        [[15, 16, 17]],
 
        [[24, 25, 26]]])]

In [82]:
np.vsplit(x, [2])

[array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],
 
        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]]), array([[[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])]

### 通用函数

使NumPy变快的关键是利用向量化操作，通常在NumPy的通用函数(ufunc)中实现

NumPy为很多类型的操作提供了非常方便的、静态类型的、可编译程序的接口，称为通用函数