In [2]:
from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [3]:
train_images.shape

(60000, 28, 28)

In [4]:
len(train_labels)

60000

In [5]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [6]:
test_images.shape

(10000, 28, 28)

In [7]:
len(test_images)

10000

In [8]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [11]:
from keras import models
from keras import layers

network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28, )))
network.add(layers.Dense(10, activation='softmax'))

In [12]:
network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

In [13]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [14]:
from keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [15]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
60000/60000 [==============================] - 3s 57us/step - loss: 0.2581 - acc: 0.9256
Epoch 2/5
60000/60000 [==============================] - 1s 18us/step - loss: 0.1048 - acc: 0.9684
Epoch 3/5
60000/60000 [==============================] - 1s 18us/step - loss: 0.0695 - acc: 0.9793
Epoch 4/5
60000/60000 [==============================] - 1s 18us/step - loss: 0.0510 - acc: 0.9844
Epoch 5/5
60000/60000 [==============================] - 1s 18us/step - loss: 0.0373 - acc: 0.9884


In [16]:
test_loss, test_acc = network.evaluate(test_images, test_labels)

10000/10000 [==============================] - 0s 25us/step


In [17]:
print('test_acc:', test_acc)

test_acc: 0.9786


In [18]:
import numpy as np

x = np.array(12)

In [19]:
x

array(12)

In [20]:
x.ndim

0

In [21]:
x = np.array([12, 3, 6, 14, 7])
x

array([12,  3,  6, 14,  7])

In [23]:
x.ndim

1