###  数据结构
- 向量


In [1]:
a <- c("k", "j", "h", "a", "c", "m")

In [2]:
a

[1] "k" "j" "h" "a" "c" "m"

In [3]:
a[3]

[1] "h"

In [4]:
a[c(1, 3, 5)]

[1] "k" "h" "c"

In [5]:
a[2:6]

[1] "j" "h" "a" "c" "m"

- 矩阵
```
myymatrix <- matrix(vector, nrow=number_of_rows, ncol=number_of_columns,
         byrow=logical_value, dimnames=list(char_vector_rownames, char_vector_colnames))
```

In [6]:
y <- matrix(1:20, nrow=5, ncol=4)
y

[,1] [,2] [,3] [,4]
[1,] 1     6   11   16  
[2,] 2     7   12   17  
[3,] 3     8   13   18  
[4,] 4     9   14   19  
[5,] 5    10   15   20

In [7]:
cells <- c(1,26,24,68)
rnames <- c("R1", "R2")
cnames <- c("C1", "C2")
mymatrix <- matrix(cells, nrow=2, ncol=2, byrow=TRUE, dimnames=list(rnames, cnames))
mymatrix

C1 C2
R1  1 26
R2 24 68

In [8]:
mymatrix <- matrix(cells, nrow=2, ncol=2, byrow=FALSE, dimnames=list(rnames, cnames))
mymatrix

C1 C2
R1  1 24
R2 26 68

In [9]:
x <- matrix(1:10, nrow=2)
x

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [10]:
x[2,]

[1]  2  4  6  8 10

In [11]:
x[,2]

[1] 3 4

In [12]:
x[1,4]

[1] 7

In [13]:
x[1, c(4,5)]

[1] 7 9

- 数组
```
myarray <- array(vector, dimensions, dimnames)
```

In [14]:
dim1 <- c("A1", "A2")
dim2 <- c("B1", "B2", "B3")
dim3 <- c("C1", "C2", "C3", "C4")
z <- array(1:24, c(2, 3, 4), dimnames=list(dim1, dim2, dim3))
z

, , C1

   B1 B2 B3
A1  1  3  5
A2  2  4  6

, , C2

   B1 B2 B3
A1  7  9 11
A2  8 10 12

, , C3

   B1 B2 B3
A1 13 15 17
A2 14 16 18

, , C4

   B1 B2 B3
A1 19 21 23
A2 20 22 24

- 数据框
```
mydata <- data.frame(col1, col2, col3,...)
```

In [15]:
patientID <- c(1, 2, 3, 4)
age <- c(25, 34, 28, 52)
diabetes <- c("Type1", "Type2", "Type1", "Type1")
status <- c("Poor", "Improved", "Excellent", "Poor")
patientdata <- data.frame(patientID, age, diabetes, status)
patientdata

patientID age diabetes status   
1 1         25  Type1    Poor     
2 2         34  Type2    Improved 
3 3         28  Type1    Excellent
4 4         52  Type1    Poor

python中对dataframe进行切片选择时返回的是行

In [16]:
patientdata[1:2]

patientID age
1 1         25 
2 2         34 
3 3         28 
4 4         52

In [17]:
patientdata[c("diabetes", "status")]

diabetes status   
1 Type1    Poor     
2 Type2    Improved 
3 Type1    Excellent
4 Type1    Poor

In [18]:
patientdata$age

[1] 25 34 28 52

列联表

In [19]:
table(patientdata$diabetes, patientdata$status)

       
        Excellent Improved Poor
  Type1         1        0    2
  Type2         0        1    0

- 因子

In [20]:
patientID <- c(1, 2, 3, 4)
age <- c(25, 34, 28, 52)
diabetes <- c("Type1", "Type2", "Type1", "Type1")
status <- c("Poor", "Improved", "Excellent", "Poor")
diabetes <- factor(diabetes)
status <- factor(status, order=TRUE)
patientdata <- data.frame(patientID, age, diabetes, status)
str(patientdata)

'data.frame':	4 obs. of  4 variables:
 $ patientID: num  1 2 3 4
 $ age      : num  25 34 28 52
 $ diabetes : Factor w/ 2 levels "Type1","Type2": 1 2 1 1
 $ status   : Ord.factor w/ 3 levels "Excellent"<"Improved"<..: 3 2 1 3


In [21]:
summary(patientdata)

   patientID         age         diabetes       status 
 Min.   :1.00   Min.   :25.00   Type1:3   Excellent:1  
 1st Qu.:1.75   1st Qu.:27.25   Type2:1   Improved :1  
 Median :2.50   Median :31.00             Poor     :2  
 Mean   :2.50   Mean   :34.75                          
 3rd Qu.:3.25   3rd Qu.:38.50                          
 Max.   :4.00   Max.   :52.00                          

- 列表
```
mylist <- list(object1, object2, ...)
mylist <- list(name1=object1, name2=object2, ...)
```

In [22]:
g <- "My First List"
h <- c(25, 26, 18, 39)
j <- matrix(1:10, nrow=5)
k <- c("one", "two", "three")
mylist <- list(title=g, ages=h, j, k)
mylist

$title
[1] "My First List"

$ages
[1] 25 26 18 39

[[3]]
     [,1] [,2]
[1,]    1    6
[2,]    2    7
[3,]    3    8
[4,]    4    9
[5,]    5   10

[[4]]
[1] "one"   "two"   "three"

### 数据的输入
- 使用键盘输入数据
- 从带分隔符的文本文件导入数据
```
mydataframe <- read.table(file, options)
```
- 导入 Excel 数据
- 导入 XML 数据
- 从网页抓取数据
- 访问数据库管理系统

In [23]:
grades <- read.table("studentgrades.csv", header=TRUE, row.names="StudentID", sep=",")
str(grades)

'data.frame':	4 obs. of  5 variables:
 $ First         : Factor w/ 4 levels "Bob","Dan","Jane",..: 1 3 2 4
 $ Last          : Factor w/ 4 levels "O'Leary","Smith",..: 2 4 3 1
 $ Math          : int  90 75 65 90
 $ Science       : int  80 NA 75 95
 $ Social.Studies: int  67 80 70 92


In [24]:
grades <- read.table("studentgrades.csv", header=TRUE,
                     row.names="StudentID", sep=",",
                     colClasses=c("character", "character", "character",
                                  "numeric", "numeric", "numeric"))
str(grades)

'data.frame':	4 obs. of  5 variables:
 $ First         : chr  "Bob" "Jane" "Dan" "Mary"
 $ Last          : chr  "Smith" "Weary" "Thornton, III" "O'Leary"
 $ Math          : num  90 75 65 90
 $ Science       : num  80 NA 75 95
 $ Social.Studies: num  67 80 70 92
