In [1]:
import numpy as np

In [8]:
%time my_arr = np.arange(10000000)

CPU times: user 21.4 ms, sys: 16.3 ms, total: 37.7 ms
Wall time: 36.8 ms


In [9]:
%time my_list = list(range(10000000))

CPU times: user 176 ms, sys: 124 ms, total: 300 ms
Wall time: 298 ms


In [10]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 140 ms, sys: 161 ms, total: 301 ms
Wall time: 305 ms


In [11]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 3.96 s, sys: 982 ms, total: 4.94 s
Wall time: 4.94 s


In [12]:
data = np.random.randn(2, 3)

In [13]:
data

array([[-0.84970067,  1.30127304, -1.09515021],
       [-1.71320967, -0.44146324, -1.00805386]])

In [14]:
data * 10

array([[ -8.49700673,  13.0127304 , -10.95150215],
       [-17.1320967 ,  -4.41463242, -10.08053861]])

In [15]:
data + data

array([[-1.69940135,  2.60254608, -2.19030043],
       [-3.42641934, -0.88292648, -2.01610772]])

In [16]:
data.shape

(2, 3)

In [17]:
data.dtype

dtype('float64')

In [18]:
data1 = [6, 7.5, 8, 0, 1]

In [19]:
arr1 = np.array(data1)

In [20]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [21]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [22]:
arr2 = np.array(data2)

In [23]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
arr2.ndim

2

In [25]:
arr2.shape

(2, 4)

In [26]:
arr1.dtype

dtype('float64')

In [27]:
arr2.dtype

dtype('int64')

In [30]:
np.empty((2, 3, 2))

array([[[6.90221571e-310, 5.02034658e+175],
        [6.01329566e-067, 3.63070438e+179],
        [7.67407084e-042, 6.12295804e+169]],

       [[5.01163108e+217, 5.49419094e-143],
        [9.80058441e+252, 1.30304358e-142],
        [2.14027814e+161, 8.82834615e+199]]])

In [31]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [36]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [37]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [38]:
arr1.dtype

dtype('float64')

In [39]:
arr2.dtype

dtype('int32')

In [40]:
arr = np.array([1, 2, 3, 4, 5])

In [41]:
arr.dtype

dtype('int64')

In [42]:
float_arr = arr.astype(np.float64)

In [43]:
float_arr.dtype

dtype('float64')

In [44]:
arr.dtype

dtype('int64')

In [45]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [46]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [47]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [48]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [49]:
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [51]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype='S10')

In [52]:
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S10')

In [53]:
numeric_strings.astype(np.float64)

array([ 1.25, -9.6 , 42.  ])

In [54]:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)

In [55]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [56]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [57]:
arr / arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [58]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [59]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [60]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [61]:
arr2 = np.array([[0, 4, 1], [7, 2, 12]], dtype=np.float64)

In [62]:
arr2 > arr1

array([[False,  True, False],
       [ True, False,  True]])

In [3]:
arr = np.arange(10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[5]

5

In [6]:
arr[5:8]

array([5, 6, 7])

In [7]:
arr[5:8] = 12

In [8]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [9]:
arr_slice = arr[5:8]

In [10]:
arr_slice

array([12, 12, 12])

In [11]:
arr_slice[1] = 12345

In [12]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [13]:
arr_slice[:] = 64

In [14]:
arr_slice

array([64, 64, 64])

In [15]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [16]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [17]:
arr2d[2]

array([7, 8, 9])

In [18]:
arr2d[0][2]

3

In [19]:
arr2d[0, 2]

3

In [20]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [21]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [22]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
arr_slice[:] = [14, 16, 17]

In [29]:
arr_slice

array([14, 16, 17])

In [30]:
old_value = arr3d[0].copy()

In [31]:
arr3d[0] = 42

In [32]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [34]:
arr3d[0] = old_value

In [35]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [36]:
arr3d[1, 0]

array([7, 8, 9])

In [47]:
x = arr3d[1]

In [48]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [49]:
y = x[0]

In [50]:
y

array([7, 8, 9])

In [51]:
z = y[0]

In [52]:
z

7

In [53]:
z = 100

In [54]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [55]:
arr

array([ 0,  1,  2,  3,  4, 14, 16, 17,  8,  9])

In [56]:
arr[1:6]

array([ 1,  2,  3,  4, 14])

In [57]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [61]:
arr3d[:2, 1:].shape

(2, 1, 3)

In [62]:
arr2d[1, :2]

array([4, 5])

In [63]:
arr2d[:2, 2]

array([3, 6])

In [64]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [67]:
arr2d[:2, 1:] = 0

In [68]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [82]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [83]:
data = np.random.randn(7, 4)

In [84]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [85]:
data

array([[ 0.18727527,  1.24557686, -0.25735083,  1.77750631],
       [-0.32220138, -1.77173777, -0.24733286,  1.17404619],
       [-1.2415709 , -0.24915664, -0.05705889, -0.86997633],
       [-0.89350711,  1.04376696, -0.04514045, -0.18059282],
       [-0.91037106, -1.23635144, -0.80063226, -1.92947269],
       [-0.51384873,  0.32253502,  1.36476717, -0.29296182],
       [ 0.32030732,  0.97892862, -0.64969385,  0.40012307]])

In [86]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [108]:
data[names == 'Bob'].shape

(2, 4)

In [117]:
data[names == 'Bob']

array([[ 0.18727527,  1.24557686, -0.25735083,  1.77750631],
       [-0.89350711,  1.04376696, -0.04514045, -0.18059282]])

In [123]:
data[names == 'Bob', [1, 2]]

array([ 1.24557686, -0.04514045])

In [97]:
data[~(names == 'Bob')]

array([[-0.32220138, -1.77173777, -0.24733286,  1.17404619],
       [-1.2415709 , -0.24915664, -0.05705889, -0.86997633],
       [-0.91037106, -1.23635144, -0.80063226, -1.92947269],
       [-0.51384873,  0.32253502,  1.36476717, -0.29296182],
       [ 0.32030732,  0.97892862, -0.64969385,  0.40012307]])

In [100]:
joe = data[names == 'Joe']

In [101]:
joe

array([[-0.32220138, -1.77173777, -0.24733286,  1.17404619],
       [-0.51384873,  0.32253502,  1.36476717, -0.29296182],
       [ 0.32030732,  0.97892862, -0.64969385,  0.40012307]])

In [102]:
joe[1] = 0

In [103]:
joe

array([[-0.32220138, -1.77173777, -0.24733286,  1.17404619],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.32030732,  0.97892862, -0.64969385,  0.40012307]])

In [104]:
data

array([[ 0.18727527,  1.24557686, -0.25735083,  1.77750631],
       [-0.32220138, -1.77173777, -0.24733286,  1.17404619],
       [-1.2415709 , -0.24915664, -0.05705889, -0.86997633],
       [-0.89350711,  1.04376696, -0.04514045, -0.18059282],
       [-0.91037106, -1.23635144, -0.80063226, -1.92947269],
       [-0.51384873,  0.32253502,  1.36476717, -0.29296182],
       [ 0.32030732,  0.97892862, -0.64969385,  0.40012307]])

In [119]:
arr2d[1:, [0, 2]]

array([[4, 0],
       [7, 9]])

In [111]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [142]:
arr = np.empty((8, 4))

In [143]:
for i in range(8):
    arr[i] = i

In [144]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [145]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [146]:
arr[:, [1, 2]]

array([[0., 0.],
       [1., 1.],
       [2., 2.],
       [3., 3.],
       [4., 4.],
       [5., 5.],
       [6., 6.],
       [7., 7.]])

In [147]:
arr_i = arr[[-3, -5, -7]]

In [148]:
arr_i

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [149]:
arr_i[0] = 100

In [150]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [135]:
arr = np.arange(32).reshape((4, 4, 2))

In [136]:
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [138]:
arr_f = arr[[1, 2], [0, 1]]

In [139]:
arr_f

array([[ 8,  9],
       [18, 19]])

In [140]:
arr_f[0] = 100

In [141]:
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [151]:
arr = np.arange(15).reshape((3, 5))

In [152]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [153]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [154]:
arrT = arr.T

In [155]:
arrT[0] = 1

In [156]:
arr

array([[ 1,  1,  2,  3,  4],
       [ 1,  6,  7,  8,  9],
       [ 1, 11, 12, 13, 14]])

In [157]:
arr = np.random.randn(6, 3)

In [158]:
arr

array([[-0.33797443,  0.28943261, -0.21647339],
       [-2.19687761, -0.634149  , -0.70728754],
       [-0.61527556,  0.03169758,  0.88310666],
       [-0.62358548,  1.0928572 ,  0.53355414],
       [ 1.01406686,  0.81755061,  0.15372977],
       [ 0.76644834,  0.42827471,  0.8044933 ]])

In [159]:
np.dot(arr.T, arr)

array([[7.32369547, 1.7516357 , 1.52341091],
       [1.7516357 , 2.533066  , 1.46718806],
       [1.52341091, 1.46718806, 2.28251611]])

In [160]:
arr = np.arange(16).reshape((2, 2, 4))

In [161]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [162]:
arr.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [166]:
arr.transpose((2, 1, 0))

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [167]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [168]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [169]:
arr = np.arange(10)

In [170]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [171]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [172]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [173]:
x = np.random.randn(8)

In [174]:
y = np.random.randn(8)

In [175]:
x

array([ 0.04081908, -0.02277734, -1.72593699, -0.6198319 ,  1.11636577,
        0.07936694,  0.2641684 ,  1.15987121])

In [176]:
y

array([ 0.20463547, -2.08041774, -0.60042363,  0.82100239,  1.5407523 ,
       -0.41006592,  1.8278621 ,  0.57088617])

In [177]:
np.maximum(x, y)

array([ 0.20463547, -0.02277734, -0.60042363,  0.82100239,  1.5407523 ,
        0.07936694,  1.8278621 ,  1.15987121])

In [180]:
arr = np.random.randn(7) * 5

In [181]:
arr

array([ 9.10250775,  6.55826069, -1.00979837, -4.15894282, -2.01114555,
       -1.0301019 ,  2.57194292])

In [182]:
remainder, whole_part = np.modf(arr)

In [183]:
remainder

array([ 0.10250775,  0.55826069, -0.00979837, -0.15894282, -0.01114555,
       -0.0301019 ,  0.57194292])

In [184]:
whole_part

array([ 9.,  6., -1., -4., -2., -1.,  2.])

In [185]:
arr

array([ 9.10250775,  6.55826069, -1.00979837, -4.15894282, -2.01114555,
       -1.0301019 ,  2.57194292])

In [186]:
np.sqrt(arr)

/home/trierbo/miniconda2/envs/pydata/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([3.01703625, 2.56091013,        nan,        nan,        nan,
              nan, 1.60372782])

In [187]:
np.sqrt(arr, arr)

/home/trierbo/miniconda2/envs/pydata/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([3.01703625, 2.56091013,        nan,        nan,        nan,
              nan, 1.60372782])

In [188]:
arr

array([3.01703625, 2.56091013,        nan,        nan,        nan,
              nan, 1.60372782])

In [189]:
np.isnan(arr)

array([False, False,  True,  True,  True,  True, False])

In [2]:
points = np.arange(-5, 5, 0.01)

In [3]:
xs, ys = np.meshgrid(points, points)

In [4]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [5]:
z = np.sqrt(xs ** 2 + ys ** 2)

In [6]:
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [7]:
%matplotlib
import matplotlib.pyplot as plt

Using matplotlib backend: Qt5Agg


In [8]:
plt.imshow(z, cmap=plt.cm.gray)

In [9]:
plt.colorbar()

In [10]:
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

Text(0.5,1,'Image plot of $\\sqrt{x^2 + y^2}$ for a grid of values')

In [11]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

In [12]:
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [13]:
cond = np.array([True, False, True, True, False])

In [16]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]

In [17]:
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [18]:
result = np.where(cond, xarr, yarr)

In [19]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [20]:
arr = np.random.randn(4, 4)

In [21]:
arr

array([[ 0.42638569,  1.10635266,  0.17169068, -0.72943865],
       [-1.13036304,  0.36974556, -0.59961957, -0.20732156],
       [-0.42900713,  1.60193547,  0.30329779, -1.25321906],
       [-0.17254141,  0.18407773, -1.04993973,  0.76628971]])

In [22]:
arr > 0

array([[ True,  True,  True, False],
       [False,  True, False, False],
       [False,  True,  True, False],
       [False,  True, False,  True]])

In [23]:
np.where(arr > 0, 2, -2)

array([[ 2,  2,  2, -2],
       [-2,  2, -2, -2],
       [-2,  2,  2, -2],
       [-2,  2, -2,  2]])

In [26]:
np.where(arr > 0, 2, arr)

array([[ 2.        ,  2.        ,  2.        , -0.72943865],
       [-1.13036304,  2.        , -0.59961957, -0.20732156],
       [-0.42900713,  2.        ,  2.        , -1.25321906],
       [-0.17254141,  2.        , -1.04993973,  2.        ]])

In [27]:
arr = np.random.randn(5, 4)

In [28]:
arr

array([[ 0.81096256,  2.16974959, -1.18224109, -1.12626707],
       [ 1.16129659, -2.2948268 , -0.87100131,  0.49839354],
       [-0.53814329,  2.35748544, -1.59011215,  0.02164928],
       [ 0.20158521,  1.01803366,  1.91895954, -0.16468875],
       [-1.11241711,  1.59265912,  0.55967262, -0.39121583]])

In [29]:
arr.mean()

0.15197668850599116

In [30]:
np.mean(arr)

0.15197668850599116

In [31]:
arr.sum()

3.039533770119823

In [32]:
arr.mean(axis=1)

array([ 0.168051  , -0.37653449,  0.06271982,  0.74347242,  0.1621747 ])

In [33]:
arr.mean(1)

array([ 0.168051  , -0.37653449,  0.06271982,  0.74347242,  0.1621747 ])

In [34]:
arr.sum(axis=0)

array([ 0.52328397,  4.84310102, -1.16472238, -1.16212883])

In [35]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])

In [36]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [37]:
arr = np.array([[0, 1, 2],
               [3, 4, 5],
               [6, 7, 8]])

In [38]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [40]:
arr.cumsum(axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]])

In [41]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

In [42]:
arr.astype(bool)

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [43]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
arr[1][1] = -1

In [45]:
arr.astype(bool)

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [46]:
arr = np.random.randn(100)

In [47]:
(arr > 0).sum()

55

In [48]:
bools = np.array([False, False, True, False])

In [49]:
bools.any()

True

In [50]:
bools.all()

False

In [51]:
arr = np.random.randn(6)

In [52]:
arr

array([-0.10834704,  0.7699354 , -1.04548496, -0.07719357,  0.97366497,
       -1.35018609])

In [53]:
arr.sort()

In [54]:
arr

array([-1.35018609, -1.04548496, -0.10834704, -0.07719357,  0.7699354 ,
        0.97366497])

In [55]:
arr = np.random.randn(5, 3)

In [56]:
arr

array([[-0.23689942,  0.38531312, -0.62740337],
       [-1.19119619,  1.52226593, -0.03779665],
       [ 0.50191408, -0.22860591,  0.2170314 ],
       [ 0.97627376,  0.9115318 , -0.20044903],
       [-1.25189832, -0.68587363, -0.56216779]])

In [57]:
arr.sort(0)

In [58]:
arr

array([[-1.25189832, -0.68587363, -0.62740337],
       [-1.19119619, -0.22860591, -0.56216779],
       [-0.23689942,  0.38531312, -0.20044903],
       [ 0.50191408,  0.9115318 , -0.03779665],
       [ 0.97627376,  1.52226593,  0.2170314 ]])

In [59]:
arr.sort()

In [60]:
arr

array([[-1.25189832, -0.68587363, -0.62740337],
       [-1.19119619, -0.56216779, -0.22860591],
       [-0.23689942, -0.20044903,  0.38531312],
       [-0.03779665,  0.50191408,  0.9115318 ],
       [ 0.2170314 ,  0.97627376,  1.52226593]])

In [61]:
arr.sort(1)

In [62]:
arr

array([[-1.25189832, -0.68587363, -0.62740337],
       [-1.19119619, -0.56216779, -0.22860591],
       [-0.23689942, -0.20044903,  0.38531312],
       [-0.03779665,  0.50191408,  0.9115318 ],
       [ 0.2170314 ,  0.97627376,  1.52226593]])

In [63]:
arr = np.random.randn(5, 3)

In [64]:
np.sort(arr)

array([[-0.72122899,  0.47421143,  0.59380838],
       [-0.05492537,  0.16564636,  1.4136669 ],
       [ 0.1512345 ,  0.5968574 ,  1.04625352],
       [-0.53996077, -0.33039538,  0.03141161],
       [-1.18329244, -0.89466411,  0.19416688]])

In [65]:
arr

array([[-0.72122899,  0.59380838,  0.47421143],
       [-0.05492537,  0.16564636,  1.4136669 ],
       [ 0.1512345 ,  0.5968574 ,  1.04625352],
       [-0.53996077, -0.33039538,  0.03141161],
       [-1.18329244,  0.19416688, -0.89466411]])

In [66]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [67]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [68]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [69]:
np.unique(ints)

array([1, 2, 3, 4])

In [70]:
values = np.array([6, 0, 0, 3, 2, 5, 6])

In [71]:
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

In [73]:
values = np.array([[6, 0, 0], [2, 5, 6]])

In [79]:
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True, False,  True])

In [75]:
np.in1d([2, 3, 6], values)

array([ True, False,  True])

In [76]:
np.unique(values)

array([0, 2, 5, 6])

In [78]:
np.union1d(values, [2, 3, 6])

array([0, 2, 3, 5, 6])

In [81]:
arr = np.arange(10)
np.save('some_array', arr)

In [82]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
np.savez('array_archive', a = arr, b = arr)

In [84]:
arch = np.load('array_archive.npz')

In [85]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
x = np.array([[1, 2, 3], [4, 5, 6]])

In [87]:
y = np.array([[6, 23], [-1, 7], [8, 9]])

In [88]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
y

array([[ 6, 23],
       [-1,  7],
       [ 8,  9]])

In [90]:
x.dot(y)

array([[ 28,  64],
       [ 67, 181]])

In [91]:
np.dot(x, y)

array([[ 28,  64],
       [ 67, 181]])

In [92]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [93]:
x @ np.ones(3)

array([ 6., 15.])

In [94]:
from numpy.linalg import inv, qr

In [95]:
X = np.random.randn(5, 5)

In [96]:
mat = X.T.dot(X)

In [97]:
mat

array([[ 3.8558786 ,  1.46917541, -1.19358703, -2.57093426, -1.68079637],
       [ 1.46917541,  4.04484228,  0.19614488,  2.44668479, -6.35931577],
       [-1.19358703,  0.19614488, 10.98204519,  7.59987755,  2.15969467],
       [-2.57093426,  2.44668479,  7.59987755, 12.40308744, -2.65430146],
       [-1.68079637, -6.35931577,  2.15969467, -2.65430146, 13.75160385]])

In [98]:
inv(mat)

array([[ 0.53621065, -0.51567742, -0.06795599,  0.22925645, -0.11800913],
       [-0.51567742,  1.545831  , -0.00938574, -0.27774029,  0.59969315],
       [-0.06795599, -0.00938574,  0.20484574, -0.15369142, -0.07448256],
       [ 0.22925645, -0.27774029, -0.15369142,  0.27201884, -0.02377601],
       [-0.11800913,  0.59969315, -0.07448256, -0.02377601,  0.34272655]])

In [99]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -4.91370245e-17, -6.48292147e-17,
         4.93886685e-17, -3.98904059e-17],
       [ 1.07845496e-16,  1.00000000e+00, -9.26506456e-17,
         4.34285096e-16, -7.09217611e-17],
       [-1.40835247e-16, -1.06041097e-16,  1.00000000e+00,
         8.30491350e-17,  4.74649727e-17],
       [ 1.58590165e-17, -1.87535525e-16,  2.49362911e-16,
         1.00000000e+00, -4.79900728e-16],
       [ 3.15812644e-16, -6.19574190e-16,  5.23568060e-17,
        -1.30699790e-16,  1.00000000e+00]])

In [100]:
q, r = qr(mat)

In [101]:
r

array([[ -5.28069177,  -2.98670678,   7.6866775 ,   8.10800944,
          6.56945971],
       [  0.        ,  -7.4876194 ,  -3.87466738, -10.55772294,
         13.63479842],
       [  0.        ,   0.        , -10.50679784,  -6.8821048 ,
         -3.45838803],
       [  0.        ,   0.        ,   0.        ,  -2.5821126 ,
         -1.02208915],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          1.4182864 ]])

In [102]:
q

array([[-0.73018437,  0.09504639, -0.45564576, -0.47135013, -0.16737074],
       [-0.27821647, -0.42922738, -0.06391974,  0.10421683,  0.85053664],
       [ 0.22602854, -0.11635552, -0.83696269,  0.47297637, -0.1056376 ],
       [ 0.48685558, -0.52096393, -0.17503085, -0.67808208, -0.03372119],
       [ 0.31829094,  0.72234895, -0.23907919, -0.28890476,  0.4860844 ]])

In [103]:
q.dot(r)

array([[ 3.8558786 ,  1.46917541, -1.19358703, -2.57093426, -1.68079637],
       [ 1.46917541,  4.04484228,  0.19614488,  2.44668479, -6.35931577],
       [-1.19358703,  0.19614488, 10.98204519,  7.59987755,  2.15969467],
       [-2.57093426,  2.44668479,  7.59987755, 12.40308744, -2.65430146],
       [-1.68079637, -6.35931577,  2.15969467, -2.65430146, 13.75160385]])

In [104]:
samples = np.random.normal(size=(4, 4))

In [105]:
samples

array([[-0.30986271,  1.44745637,  0.95377241,  0.54653942],
       [ 0.54577387,  0.47941069, -1.91021305, -0.35557296],
       [ 0.72340831,  1.86439589, -0.09914663, -1.95496859],
       [ 0.53543795,  0.58566975,  2.12683278, -0.75256811]])

In [106]:
from random import normalvariate

In [107]:
N = 1000000

In [108]:
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

613 ms ± 14.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [109]:
%timeit np.random.normal(size=N)

41.4 ms ± 563 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [110]:
np.random.seed(1234)

In [111]:
np.random.normal(size=(4, 4))

array([[ 4.71435164e-01, -1.19097569e+00,  1.43270697e+00,
        -3.12651896e-01],
       [-7.20588733e-01,  8.87162940e-01,  8.59588414e-01,
        -6.36523504e-01],
       [ 1.56963721e-02, -2.24268495e+00,  1.15003572e+00,
         9.91946022e-01],
       [ 9.53324128e-01, -2.02125482e+00, -3.34077366e-01,
         2.11836468e-03]])

In [112]:
np.random.normal(size=(4, 4))

array([[ 0.40545341,  0.28909194,  1.32115819, -1.54690555],
       [-0.20264632, -0.65596934,  0.19342138,  0.55343891],
       [ 1.31815155, -0.46930528,  0.67555409, -1.81702723],
       [-0.18310854,  1.05896919, -0.39784023,  0.33743765]])

In [113]:
rng = np.random.RandomState(1234)

In [122]:
x = rng.randn(10)

In [115]:
rng.randn(10)

array([ 1.15003572,  0.99194602,  0.95332413, -2.02125482, -0.33407737,
        0.00211836,  0.40545341,  0.28909194,  1.32115819, -1.54690555])

In [116]:
np.random.seed(1234)
np.random.normal(size=(4, 4))

array([[ 4.71435164e-01, -1.19097569e+00,  1.43270697e+00,
        -3.12651896e-01],
       [-7.20588733e-01,  8.87162940e-01,  8.59588414e-01,
        -6.36523504e-01],
       [ 1.56963721e-02, -2.24268495e+00,  1.15003572e+00,
         9.91946022e-01],
       [ 9.53324128e-01, -2.02125482e+00, -3.34077366e-01,
         2.11836468e-03]])

In [117]:
np.random.seed()

In [118]:
np.random.normal(size=(4, 4))

array([[ 0.97388767, -0.29403851,  0.24258125, -0.44061622],
       [-0.11686508, -0.31700928,  1.87702341,  0.78915126],
       [-1.94442715, -0.48000771,  0.35152726, -0.60968651],
       [ 1.54500468,  0.19349007,  0.61156741, -0.7535754 ]])

In [119]:
np.random.seed()
np.random.normal(size=(4, 4))

array([[ 0.76333708,  0.13068947,  2.14221346, -1.3081902 ],
       [ 1.20315925, -1.98446452, -2.09719994,  0.63969995],
       [-0.7291946 , -0.48568418,  1.52229809, -0.76346691],
       [-1.26353994, -0.90188496, -1.4866997 , -0.30881889]])

In [123]:
np.random.permutation(x)

array([ 0.86371729,  1.04593826,  2.39096052,  1.04757857,  0.12471295,
       -0.12209157, -0.32279481,  0.33743765, -0.39784023,  0.84167471])

In [124]:
x

array([-0.39784023,  0.33743765,  1.04757857,  1.04593826,  0.86371729,
       -0.12209157,  0.12471295, -0.32279481,  0.84167471,  2.39096052])

In [125]:
np.random.permutation(x)

array([-0.32279481,  2.39096052, -0.12209157, -0.39784023,  1.04593826,
        0.84167471,  1.04757857,  0.12471295,  0.86371729,  0.33743765])

In [126]:
np.random.permutation?

In [127]:
import random

position = 0
walk = [position]
steps = 1000

for i in range(steps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)

In [128]:
plt.plot(walk[:100])

In [137]:
nsteps = 1000
draws = np.random.randint(0, 2, size = nsteps)
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()

In [138]:
plt.plot(walk[:100])

In [139]:
(np.abs(walk) >= 10).argmax()

125

In [140]:
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0, 2, size=(nwalks, nsteps))
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(axis=1)

In [141]:
walks

array([[  1,   0,  -1, ...,  40,  41,  42],
       [ -1,  -2,  -1, ..., -42, -43, -44],
       [  1,   0,  -1, ...,   0,  -1,  -2],
       ...,
       [  1,   0,   1, ...,  34,  33,  32],
       [  1,   0,  -1, ...,  -8,  -9, -10],
       [  1,   0,  -1, ...,  34,  33,  34]])

In [142]:
walks.max(1)

array([42,  4, 10, ..., 51,  4, 41])

In [143]:
walks.max()

125

In [144]:
hits30 = (np.abs(walks) >= 30).any(1)

In [145]:
hits30

array([ True,  True, False, ...,  True,  True,  True])

In [146]:
hits30.sum()

3441

In [147]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)

In [148]:
crossing_times

array([723, 755, 833, ..., 577, 563, 695])

In [149]:
crossing_times.shape

(3441,)

In [150]:
crossing_times.mean()

496.76053472827664