In [1]:
import numpy as np

In [2]:
%time my_arr = np.arange(10000000)

CPU times: user 18.9 ms, sys: 16 ms, total: 34.9 ms
Wall time: 34.2 ms


In [3]:
%time my_list = list(range(10000000))

CPU times: user 154 ms, sys: 113 ms, total: 267 ms
Wall time: 264 ms


In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 174 ms, sys: 223 ms, total: 397 ms
Wall time: 386 ms


In [5]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 4.37 s, sys: 1.18 s, total: 5.55 s
Wall time: 5.56 s


In [6]:
data = np.random.randn(2, 3)

In [7]:
data

array([[ 0.42751722, -0.61633443, -1.15130669],
       [ 1.08955727, -0.1348633 , -1.27042993]])

In [8]:
data * 10

array([[  4.27517223,  -6.16334427, -11.51306685],
       [ 10.89557268,  -1.348633  , -12.70429929]])

In [9]:
data + data

array([[ 0.85503445, -1.23266885, -2.30261337],
       [ 2.17911454, -0.2697266 , -2.54085986]])

In [10]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

In [12]:
data1 = [6, 7.5, 8, 0, 1]

In [13]:
arr1 = np.array(data1)

In [14]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [15]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [16]:
arr2 = np.array(data2)

In [17]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr2.ndim

2

In [19]:
arr2.shape

(2, 4)

In [20]:
arr1.dtype

dtype('float64')

In [21]:
arr2.dtype

dtype('int64')

In [22]:
np.empty((2, 3, 2))

array([[[6.95145506e-310, 6.95145506e-310],
        [6.95145505e-310, 6.95145098e-310],
        [6.95145099e-310, 6.95145501e-310]],

       [[6.95145505e-310, 6.95145503e-310],
        [6.95145395e-310, 6.95145501e-310],
        [6.95145505e-310, 6.95145395e-310]]])

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [25]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [26]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [27]:
arr1.dtype

dtype('float64')

In [28]:
arr2.dtype

dtype('int32')

In [29]:
arr = np.array([1, 2, 3, 4, 5])

In [30]:
arr.dtype

dtype('int64')

In [31]:
float_arr = arr.astype(np.float64)

In [32]:
float_arr.dtype

dtype('float64')

In [33]:
arr.dtype

dtype('int64')

In [34]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [35]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [36]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [37]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [38]:
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [39]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype='S10')

In [40]:
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S10')

In [41]:
numeric_strings.astype(np.float64)

array([ 1.25, -9.6 , 42.  ])

In [42]:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)

In [43]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [44]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [45]:
arr / arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [46]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [48]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [49]:
arr2 = np.array([[0, 4, 1], [7, 2, 12]], dtype=np.float64)

In [50]:
arr2 > arr1

array([[False,  True, False],
       [ True, False,  True]])

In [51]:
arr = np.arange(10)

In [52]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr[5]

5

In [54]:
arr[5:8]

array([5, 6, 7])

In [55]:
arr[5:8] = 12

In [56]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [57]:
arr_slice = arr[5:8]

In [58]:
arr_slice

array([12, 12, 12])

In [59]:
arr_slice[1] = 12345

In [60]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [61]:
arr_slice[:] = 64

In [62]:
arr_slice

array([64, 64, 64])

In [63]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [64]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [65]:
arr2d[2]

array([7, 8, 9])

In [66]:
arr2d[0][2]

3

In [67]:
arr2d[0, 2]

3

In [68]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [69]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [70]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
arr_slice[:] = [14, 16, 17]

In [72]:
arr_slice

array([14, 16, 17])

In [73]:
old_value = arr3d[0].copy()

In [74]:
arr3d[0] = 42

In [75]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [76]:
arr3d[0] = old_value

In [77]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [78]:
arr3d[1, 0]

array([7, 8, 9])

In [79]:
x = arr3d[1]

In [80]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [81]:
y = x[0]

In [82]:
y

array([7, 8, 9])

In [83]:
z = y[0]

In [84]:
z

7

In [85]:
z = 100

In [86]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [87]:
arr

array([ 0,  1,  2,  3,  4, 14, 16, 17,  8,  9])

In [88]:
arr[1:6]

array([ 1,  2,  3,  4, 14])

In [89]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [92]:
arr3d[:2, 1:].shape

(2, 1, 3)

In [93]:
arr2d[1, :2]

array([4, 5])

In [94]:
arr2d[:2, 2]

array([3, 6])

In [95]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [96]:
arr2d[:2, 1:] = 0

In [97]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [98]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [99]:
data = np.random.randn(7, 4)

In [100]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [101]:
data

array([[-0.39031194, -1.63116126,  0.96301339,  1.60403421],
       [-0.36288182,  2.6246137 ,  0.0673943 ,  0.12666832],
       [ 0.31107639,  0.43697445,  1.63166249, -0.05341128],
       [-0.65531026,  1.04298475, -0.68318238, -0.40303028],
       [-0.85041872, -2.08017777,  0.18114073, -0.05458237],
       [-0.36017028,  0.12727875, -0.14430347, -0.71526551],
       [ 0.46694265,  0.55367888,  0.70529688, -0.03650557]])

In [102]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [103]:
data[names == 'Bob'].shape

(2, 4)

In [104]:
data[names == 'Bob']

array([[-0.39031194, -1.63116126,  0.96301339,  1.60403421],
       [-0.65531026,  1.04298475, -0.68318238, -0.40303028]])

In [105]:
data[names == 'Bob', [1, 2]]

array([-1.63116126, -0.68318238])

In [106]:
data[~(names == 'Bob')]

array([[-0.36288182,  2.6246137 ,  0.0673943 ,  0.12666832],
       [ 0.31107639,  0.43697445,  1.63166249, -0.05341128],
       [-0.85041872, -2.08017777,  0.18114073, -0.05458237],
       [-0.36017028,  0.12727875, -0.14430347, -0.71526551],
       [ 0.46694265,  0.55367888,  0.70529688, -0.03650557]])

In [107]:
joe = data[names == 'Joe']

In [108]:
joe

array([[-0.36288182,  2.6246137 ,  0.0673943 ,  0.12666832],
       [-0.36017028,  0.12727875, -0.14430347, -0.71526551],
       [ 0.46694265,  0.55367888,  0.70529688, -0.03650557]])

In [109]:
joe[1] = 0

In [110]:
joe

array([[-0.36288182,  2.6246137 ,  0.0673943 ,  0.12666832],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.46694265,  0.55367888,  0.70529688, -0.03650557]])

In [111]:
data

array([[-0.39031194, -1.63116126,  0.96301339,  1.60403421],
       [-0.36288182,  2.6246137 ,  0.0673943 ,  0.12666832],
       [ 0.31107639,  0.43697445,  1.63166249, -0.05341128],
       [-0.65531026,  1.04298475, -0.68318238, -0.40303028],
       [-0.85041872, -2.08017777,  0.18114073, -0.05458237],
       [-0.36017028,  0.12727875, -0.14430347, -0.71526551],
       [ 0.46694265,  0.55367888,  0.70529688, -0.03650557]])

In [112]:
arr2d[1:, [0, 2]]

array([[4, 0],
       [7, 9]])

In [113]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [114]:
arr = np.empty((8, 4))

In [115]:
for i in range(8):
    arr[i] = i

In [116]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [117]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [118]:
arr[:, [1, 2]]

array([[0., 0.],
       [1., 1.],
       [2., 2.],
       [3., 3.],
       [4., 4.],
       [5., 5.],
       [6., 6.],
       [7., 7.]])

In [119]:
arr_i = arr[[-3, -5, -7]]

In [120]:
arr_i

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [121]:
arr_i[0] = 100

In [122]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [123]:
arr = np.arange(32).reshape((4, 4, 2))

In [124]:
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [125]:
arr_f = arr[[1, 2], [0, 1]]

In [126]:
arr_f

array([[ 8,  9],
       [18, 19]])

In [127]:
arr_f[0] = 100

In [128]:
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [129]:
arr = np.arange(15).reshape((3, 5))

In [130]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [131]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [132]:
arrT = arr.T

In [133]:
arrT[0] = 1

In [134]:
arr

array([[ 1,  1,  2,  3,  4],
       [ 1,  6,  7,  8,  9],
       [ 1, 11, 12, 13, 14]])

In [135]:
arr = np.random.randn(6, 3)

In [136]:
arr

array([[ 0.60536453,  0.37476694,  0.03664145],
       [-0.51925753,  0.66794204, -0.19708051],
       [ 0.80698513,  1.48618685,  0.29439046],
       [ 1.22764112, -0.17657579,  0.32125564],
       [-0.35259372,  0.60690006,  2.2813824 ],
       [ 0.04149517,  1.63965044,  0.94953223]])

In [137]:
np.dot(arr.T, arr)

array([[ 2.92046649,  0.71664409, -0.00852776],
       [ 0.71664409,  5.88330845,  3.20435897],
       [-0.00852776,  3.20435897,  6.33637137]])

In [138]:
arr = np.arange(16).reshape((2, 2, 4))

In [139]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [140]:
arr.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [141]:
arr.transpose((2, 1, 0))

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [142]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [143]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [144]:
arr = np.arange(10)

In [145]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [147]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [148]:
x = np.random.randn(8)

In [149]:
y = np.random.randn(8)

In [150]:
x

array([ 0.65343043,  0.93908699,  0.04134668,  1.4320219 ,  1.35572446,
        1.06514779,  0.20601868, -0.59088492])

In [151]:
y

array([ 0.60129727,  1.14489967, -0.39535215,  0.2007657 , -0.53797234,
        1.05601068,  0.76568649, -0.08647143])

In [152]:
np.maximum(x, y)

array([ 0.65343043,  1.14489967,  0.04134668,  1.4320219 ,  1.35572446,
        1.06514779,  0.76568649, -0.08647143])

In [153]:
arr = np.random.randn(7) * 5

In [154]:
arr

array([ 3.57020654,  5.22266421,  7.69179747, -2.63856058,  8.53109851,
        1.93103166,  0.93166301])

In [155]:
remainder, whole_part = np.modf(arr)

In [156]:
remainder

array([ 0.57020654,  0.22266421,  0.69179747, -0.63856058,  0.53109851,
        0.93103166,  0.93166301])

In [157]:
whole_part

array([ 3.,  5.,  7., -2.,  8.,  1.,  0.])

In [158]:
arr

array([ 3.57020654,  5.22266421,  7.69179747, -2.63856058,  8.53109851,
        1.93103166,  0.93166301])

In [159]:
np.sqrt(arr)

/home/trierbo/miniconda2/envs/pydata/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([1.88949902, 2.2853149 , 2.773409  ,        nan, 2.92080443,
       1.38961565, 0.96522692])

In [160]:
np.sqrt(arr, arr)

/home/trierbo/miniconda2/envs/pydata/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([1.88949902, 2.2853149 , 2.773409  ,        nan, 2.92080443,
       1.38961565, 0.96522692])

In [161]:
arr

array([1.88949902, 2.2853149 , 2.773409  ,        nan, 2.92080443,
       1.38961565, 0.96522692])

In [162]:
np.isnan(arr)

array([False, False, False,  True, False, False, False])

In [163]:
points = np.arange(-5, 5, 0.01)

In [164]:
xs, ys = np.meshgrid(points, points)

In [165]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [166]:
z = np.sqrt(xs ** 2 + ys ** 2)

In [167]:
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [168]:
%matplotlib
import matplotlib.pyplot as plt

Using matplotlib backend: Qt5Agg


In [169]:
plt.imshow(z, cmap=plt.cm.gray)

In [170]:
plt.colorbar()

In [171]:
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

Text(0.5,1,'Image plot of $\\sqrt{x^2 + y^2}$ for a grid of values')

In [172]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

In [173]:
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [174]:
cond = np.array([True, False, True, True, False])

In [175]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]

In [176]:
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [177]:
result = np.where(cond, xarr, yarr)

In [178]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [179]:
arr = np.random.randn(4, 4)

In [180]:
arr

array([[ 0.69107593,  2.83375103, -1.68145209, -1.47311649],
       [-1.73557787, -0.24505127,  0.02678772,  0.19363284],
       [-0.83509162,  1.19309289,  0.2886387 ,  1.00429996],
       [-0.23017256, -0.57222994, -0.68148284, -0.27655666]])

In [181]:
arr > 0

array([[ True,  True, False, False],
       [False, False,  True,  True],
       [False,  True,  True,  True],
       [False, False, False, False]])

In [182]:
np.where(arr > 0, 2, -2)

array([[ 2,  2, -2, -2],
       [-2, -2,  2,  2],
       [-2,  2,  2,  2],
       [-2, -2, -2, -2]])

In [183]:
np.where(arr > 0, 2, arr)

array([[ 2.        ,  2.        , -1.68145209, -1.47311649],
       [-1.73557787, -0.24505127,  2.        ,  2.        ],
       [-0.83509162,  2.        ,  2.        ,  2.        ],
       [-0.23017256, -0.57222994, -0.68148284, -0.27655666]])

In [184]:
arr = np.random.randn(5, 4)

In [185]:
arr

array([[-0.16097294, -0.29340975,  0.83145912, -1.0644022 ],
       [-0.34123371, -0.06712232, -0.26419667, -0.31572943],
       [-2.11323515, -0.02871619, -0.31054742,  0.337521  ],
       [ 1.38040217,  0.88641591,  0.25740519, -0.62083463],
       [ 1.17642949,  0.46535429, -0.71751775,  0.96494301]])

In [186]:
arr.mean()

0.00010059983740752787

In [187]:
np.mean(arr)

0.00010059983740752787

In [188]:
arr.sum()

0.0020119967481505574

In [189]:
arr.mean(axis=1)

array([-0.17183144, -0.24707053, -0.52874444,  0.47584716,  0.47230226])

In [190]:
arr.mean(1)

array([-0.17183144, -0.24707053, -0.52874444,  0.47584716,  0.47230226])

In [191]:
arr.sum(axis=0)

array([-0.05861014,  0.96252194, -0.20339754, -0.69850226])

In [192]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])

In [193]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [194]:
arr = np.array([[0, 1, 2],
               [3, 4, 5],
               [6, 7, 8]])

In [195]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [196]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [197]:
arr.cumsum(axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]])

In [198]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

In [199]:
arr.astype(bool)

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [200]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [201]:
arr[1][1] = -1

In [202]:
arr.astype(bool)

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [203]:
arr = np.random.randn(100)

In [204]:
(arr > 0).sum()

52

In [205]:
bools = np.array([False, False, True, False])

In [206]:
bools.any()

True

In [207]:
bools.all()

False

In [208]:
arr = np.random.randn(6)

In [209]:
arr

array([-0.67898198,  0.45569222, -1.28417486,  0.45604479,  1.26033504,
        1.33940383])

In [210]:
arr.sort()

In [211]:
arr

array([-1.28417486, -0.67898198,  0.45569222,  0.45604479,  1.26033504,
        1.33940383])

In [212]:
arr = np.random.randn(5, 3)

In [213]:
arr

array([[ 3.07386709,  0.595586  , -0.75558933],
       [ 0.2090895 , -1.18880454,  1.5840943 ],
       [ 0.87807931,  1.31072571,  0.94169725],
       [ 0.75604381, -0.71428986, -0.76393511],
       [-1.14974502,  0.06833579, -0.19737125]])

In [214]:
arr.sort(0)

In [215]:
arr

array([[-1.14974502, -1.18880454, -0.76393511],
       [ 0.2090895 , -0.71428986, -0.75558933],
       [ 0.75604381,  0.06833579, -0.19737125],
       [ 0.87807931,  0.595586  ,  0.94169725],
       [ 3.07386709,  1.31072571,  1.5840943 ]])

In [216]:
arr.sort()

In [217]:
arr

array([[-1.18880454, -1.14974502, -0.76393511],
       [-0.75558933, -0.71428986,  0.2090895 ],
       [-0.19737125,  0.06833579,  0.75604381],
       [ 0.595586  ,  0.87807931,  0.94169725],
       [ 1.31072571,  1.5840943 ,  3.07386709]])

In [218]:
arr.sort(1)

In [219]:
arr

array([[-1.18880454, -1.14974502, -0.76393511],
       [-0.75558933, -0.71428986,  0.2090895 ],
       [-0.19737125,  0.06833579,  0.75604381],
       [ 0.595586  ,  0.87807931,  0.94169725],
       [ 1.31072571,  1.5840943 ,  3.07386709]])

In [220]:
arr = np.random.randn(5, 3)

In [221]:
np.sort(arr)

array([[-1.57834972, -1.13661106,  1.67666293],
       [ 0.30549595,  0.65868424,  0.91361408],
       [-0.92041427, -0.67087411,  0.43247192],
       [-0.58083146,  0.57364186,  1.40023468],
       [-1.81608718, -0.63032356,  0.46848598]])

In [222]:
arr

array([[-1.57834972, -1.13661106,  1.67666293],
       [ 0.30549595,  0.91361408,  0.65868424],
       [-0.67087411,  0.43247192, -0.92041427],
       [-0.58083146,  1.40023468,  0.57364186],
       [ 0.46848598, -0.63032356, -1.81608718]])

In [223]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [224]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [225]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [226]:
np.unique(ints)

array([1, 2, 3, 4])

In [227]:
values = np.array([6, 0, 0, 3, 2, 5, 6])

In [228]:
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

In [229]:
values = np.array([[6, 0, 0], [2, 5, 6]])

In [230]:
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True, False,  True])

In [231]:
np.in1d([2, 3, 6], values)

array([ True, False,  True])

In [232]:
np.unique(values)

array([0, 2, 5, 6])

In [233]:
np.union1d(values, [2, 3, 6])

array([0, 2, 3, 5, 6])

In [234]:
arr = np.arange(10)
np.save('some_array', arr)

In [235]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [236]:
np.savez('array_archive', a = arr, b = arr)

In [237]:
arch = np.load('array_archive.npz')

In [238]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [239]:
x = np.array([[1, 2, 3], [4, 5, 6]])

In [240]:
y = np.array([[6, 23], [-1, 7], [8, 9]])

In [241]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [242]:
y

array([[ 6, 23],
       [-1,  7],
       [ 8,  9]])

In [243]:
x.dot(y)

array([[ 28,  64],
       [ 67, 181]])

In [244]:
np.dot(x, y)

array([[ 28,  64],
       [ 67, 181]])

In [245]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [246]:
x @ np.ones(3)

array([ 6., 15.])

In [247]:
from numpy.linalg import inv, qr

In [248]:
X = np.random.randn(5, 5)

In [249]:
mat = X.T.dot(X)

In [250]:
mat

array([[ 6.14863718,  1.73775058, -1.14530999,  0.16778791, -1.50051849],
       [ 1.73775058,  5.55512546,  0.64852607,  1.1185552 , -3.76673211],
       [-1.14530999,  0.64852607,  3.94116759,  1.54499819, -1.85170052],
       [ 0.16778791,  1.1185552 ,  1.54499819,  3.99356598,  0.57035732],
       [-1.50051849, -3.76673211, -1.85170052,  0.57035732,  4.64558061]])

In [251]:
inv(mat)

array([[ 0.30825721,  0.31551825,  0.44989364, -0.35802175,  0.57867621],
       [ 0.31551825,  1.5109006 ,  1.23534135, -1.19516107,  1.96611588],
       [ 0.44989364,  1.23534135,  1.57824569, -1.25107536,  1.92963437],
       [-0.35802175, -1.19516107, -1.25107536,  1.33372458, -1.74711989],
       [ 0.57867621,  1.96611588,  1.92963437, -1.74711989,  2.97997923]])

In [252]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -5.99100233e-17,  6.86619868e-17,
        -1.61854147e-16, -1.81014304e-16],
       [ 2.35552071e-16,  1.00000000e+00,  6.74674393e-16,
        -3.31750629e-16,  9.89592068e-16],
       [ 1.37436501e-16, -2.98848357e-16,  1.00000000e+00,
         9.89671272e-16, -1.28513203e-15],
       [ 2.52767963e-16,  7.41170966e-16,  6.73070252e-16,
         1.00000000e+00,  1.38263575e-15],
       [-3.84279560e-16,  8.62843236e-16, -1.23694156e-15,
         9.46280691e-17,  1.00000000e+00]])

In [253]:
q, r = qr(mat)

In [254]:
r

array([[-6.664605  , -3.81645846,  1.10902819, -0.15307365,  3.07986656],
       [ 0.        , -5.93075571, -2.88393535, -1.55826703,  5.03132695],
       [ 0.        ,  0.        , -3.67884637, -2.01478452,  1.2636536 ],
       [ 0.        ,  0.        ,  0.        , -3.66459143, -2.30831925],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.22441237]])

In [255]:
q

array([[-0.92258089,  0.30067687, -0.20250665, -0.023766  ,  0.1298621 ],
       [-0.26074322, -0.768875  ,  0.34785039, -0.15864614,  0.44122071],
       [ 0.17184964, -0.21993539, -0.84708675,  0.13046789,  0.43303381],
       [-0.02517597, -0.17240166, -0.29240792, -0.85464519, -0.39207531],
       [ 0.2251474 ,  0.4902354 ,  0.18690319, -0.47626286,  0.66874419]])

In [256]:
q.dot(r)

array([[ 6.14863718,  1.73775058, -1.14530999,  0.16778791, -1.50051849],
       [ 1.73775058,  5.55512546,  0.64852607,  1.1185552 , -3.76673211],
       [-1.14530999,  0.64852607,  3.94116759,  1.54499819, -1.85170052],
       [ 0.16778791,  1.1185552 ,  1.54499819,  3.99356598,  0.57035732],
       [-1.50051849, -3.76673211, -1.85170052,  0.57035732,  4.64558061]])

In [257]:
samples = np.random.normal(size=(4, 4))

In [258]:
samples

array([[-6.74034092e-01,  9.19949607e-01, -1.47830755e-02,
         5.61677426e-01],
       [-5.25881307e-01, -6.79833235e-01,  6.76045148e-01,
        -2.12840919e-01],
       [-4.58324359e-01, -3.38753165e-01, -1.29293130e+00,
         1.67776932e+00],
       [ 2.98147584e-01,  1.10185507e+00,  7.10217133e-04,
         3.75652992e-01]])

In [259]:
from random import normalvariate

In [260]:
N = 1000000

In [261]:
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

754 ms ± 60.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [262]:
%timeit np.random.normal(size=N)

51 ms ± 2.97 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [263]:
np.random.seed(1234)

In [264]:
np.random.normal(size=(4, 4))

array([[ 4.71435164e-01, -1.19097569e+00,  1.43270697e+00,
        -3.12651896e-01],
       [-7.20588733e-01,  8.87162940e-01,  8.59588414e-01,
        -6.36523504e-01],
       [ 1.56963721e-02, -2.24268495e+00,  1.15003572e+00,
         9.91946022e-01],
       [ 9.53324128e-01, -2.02125482e+00, -3.34077366e-01,
         2.11836468e-03]])

In [265]:
np.random.normal(size=(4, 4))

array([[ 0.40545341,  0.28909194,  1.32115819, -1.54690555],
       [-0.20264632, -0.65596934,  0.19342138,  0.55343891],
       [ 1.31815155, -0.46930528,  0.67555409, -1.81702723],
       [-0.18310854,  1.05896919, -0.39784023,  0.33743765]])

In [266]:
rng = np.random.RandomState(1234)

In [267]:
x = rng.randn(10)

In [268]:
rng.randn(10)

array([ 1.15003572,  0.99194602,  0.95332413, -2.02125482, -0.33407737,
        0.00211836,  0.40545341,  0.28909194,  1.32115819, -1.54690555])

In [269]:
np.random.seed(1234)
np.random.normal(size=(4, 4))

array([[ 4.71435164e-01, -1.19097569e+00,  1.43270697e+00,
        -3.12651896e-01],
       [-7.20588733e-01,  8.87162940e-01,  8.59588414e-01,
        -6.36523504e-01],
       [ 1.56963721e-02, -2.24268495e+00,  1.15003572e+00,
         9.91946022e-01],
       [ 9.53324128e-01, -2.02125482e+00, -3.34077366e-01,
         2.11836468e-03]])

In [270]:
np.random.seed()

In [271]:
np.random.normal(size=(4, 4))

array([[-0.35451439,  1.09111081, -0.4103819 ,  0.48322161],
       [-1.01497932,  0.32754315,  0.91339952,  0.57024107],
       [-0.84409629, -0.0641977 , -0.17252258,  1.36228129],
       [-1.39840925, -0.41341735, -0.27788731,  0.66267362]])

In [272]:
np.random.seed()
np.random.normal(size=(4, 4))

array([[-1.035085  ,  0.08002319, -1.85118561, -0.13563069],
       [-1.07474454,  1.85512513, -1.09608529,  0.35292714],
       [ 0.50871416,  0.0204248 ,  0.24164093,  0.72016113],
       [-0.00332702, -1.64288995,  1.32805631,  0.93924682]])

In [273]:
np.random.permutation(x)

array([-0.3126519 , -0.72058873,  0.88716294,  1.43270697,  0.47143516,
       -1.19097569, -2.24268495,  0.01569637,  0.85958841, -0.6365235 ])

In [274]:
x

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])

In [275]:
np.random.permutation(x)

array([-2.24268495,  1.43270697,  0.01569637, -0.6365235 ,  0.47143516,
        0.85958841, -0.72058873, -0.3126519 , -1.19097569,  0.88716294])

In [276]:
np.random.permutation?

In [277]:
import random

position = 0
walk = [position]
steps = 1000

for i in range(steps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)

In [278]:
plt.plot(walk[:100])

In [279]:
nsteps = 1000
draws = np.random.randint(0, 2, size = nsteps)
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()

In [280]:
plt.plot(walk[:100])

In [281]:
(np.abs(walk) >= 10).argmax()

171

In [282]:
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0, 2, size=(nwalks, nsteps))
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(axis=1)

In [283]:
walks

array([[-1, -2, -3, ..., 68, 67, 66],
       [ 1,  0,  1, ...,  4,  5,  4],
       [ 1,  0,  1, ...,  8,  7,  8],
       ...,
       [-1,  0,  1, ..., 54, 55, 56],
       [ 1,  0, -1, ..., 44, 43, 42],
       [ 1,  2,  1, ..., 78, 77, 78]])

In [284]:
walks.max(1)

array([72, 17, 21, ..., 64, 46, 87])

In [285]:
walks.max()

114

In [286]:
hits30 = (np.abs(walks) >= 30).any(1)

In [287]:
hits30

array([ True, False, False, ...,  True,  True,  True])

In [288]:
hits30.sum()

3385

In [289]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)

In [290]:
crossing_times

array([397, 863, 829, ..., 463, 757, 605])

In [291]:
crossing_times.shape

(3385,)

In [292]:
crossing_times.mean()

500.5911373707533